const SpotifyActionTypes = {
  GET_PLAY_STATUS: "GET_PLAY_STATUS",

  // get spotify songs using data retrieved from GET_DS_SONGS
  GET_SPOTIFY_SONGS_FETCHING: "GET_SPOTIFY_SONGS_FETCHING",
  GET_SPOTIFY_SONGS_SUCCESS: "GET_SPOTIFY_SONGS_SUCCESS",
  GET_SPOTIFY_SONGS_FAILURE: "GET_SPOTIFY_SONGS_FAILURE",
  GET_SPOTIFY_USER_FETCHING: "GET_SPOTIFY_USER_FETCHING",
  GET_SPOTIFY_USER_SUCCESS: "GET_SPOTIFY_USER_SUCCESS",
  GET_SPOTIFY_USER_FAILURE: "GET_SPOTIFY_USER_FAILURE",
  GET_CURRENT_SONG_FETCHING: "GET_CURRENT_SONG_FETCHING",
  GET_CURRENT_SONG_SUCCESS: "GET_CURRENT_SONG_SUCCESS",
  GET_CURRENT_SONG_FAILURE: "GET_CURRENT_SONG_FAILURE"
};

export default SpotifyActionTypes;
